name: Upload to S3

on:
  push:
    branches: [ main ]
    paths: [ "lambdas/**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Zip and upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1' 
        S3_BUCKET: 'lambdas.bryval.tech' 
      run: |
        cd lambdas
        zip getCount.zip getCount/lambda_function.py
        python -c "import boto3; boto3.client('s3').upload_file('getCount.zip', '${S3_BUCKET}', 'getCount.zip')"
        zip updateCount.zip updateCount/lambda_function.py
        python -c "import boto3; boto3.client('s3').upload_file('updateCount.zip', '${S3_BUCKET}', 'updateCount.zip')"