# Unused
name: Zip Lambda Functions

on:
  workflow_dispatch:

jobs:
  zip-lambda-functions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Zip Lambda Functions
      run: |
        zip_lambda_functions() {
            folder_names=("$@")
            for folder_name in "${folder_names[@]}"; do
                lambda_file="lambdas/${folder_name}/lambda_function.py"
                zip_file="lambdas/${folder_name}/${folder_name}.zip"
                zip -j "${zip_file}" "${lambda_file}"
            done
        }

        folders=("getCount" "updateCount")
        zip_lambda_functions "${folders[@]}"
      shell: bash