name: Zip Lambda Functions

on:
  workflow_dispatch:

jobs:
  zip-lambda-functions:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PowerShell
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Zip Lambda Functions
      run: |
        function Zip-LambdaFunctions {
            param (
                [Parameter(Mandatory=$true)]
                [string[]]$folderNames
            )

            foreach ($folderName in $folderNames) {
                $lambda_file = "..\lambdas\$folderName\lambda_function.py"
                $lambda_dir = Split-Path -Parent $lambda_file
                $zip_file = "..\lambdas\$folderName\$folderName.zip"
                Compress-Archive -Path $lambda_file -DestinationPath $zip_file -Force
            }
        }

        $folders = @("getCount", "updateCount")
        Zip-LambdaFunctions -folderNames $folders
      shell: pwsh